apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-wm-msr
  namespace: default
spec:
  project: default
  source:
    chart: webmethods/microservicesruntime
    repoURL: https://ibm.github.io/webmethods-helm-charts/charts
    targetRevision: 1.0.7
    helm:
      releaseName: wm-msr
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default