apiVersion: v1
kind: ServiceAccount
metadata:
  name: wm-sa
  namespace: webmethods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wm-sa-anyuid-binding
  namespace: webmethods
subjects:
  - kind: ServiceAccount
    name: wm-sa
    namespace: webmethods
roleRef:
  kind: ClusterRole
  name: anyuid
  apiGroup: rbac.authorization.k8s.io
---
# apiVersion: v1 # For non ocp envs
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: custom-privileged-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny 
users:
  - system:serviceaccount:webmethods:wm-sa